import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { indonesiaOnlineTerms } from "../data/terms";
import { indonesiaOfflineTerms } from "../data/terms";

export default function Home() {
  const [showModal, setShowModal] = useState(false);
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [redirectLink, setRedirectLink] = useState("");
  const [termsContent, setTermsContent] = useState("");

  const handleOpenModal = (link, terms) => {
    setRedirectLink(link); // Set link tujuan redirect
    setTermsContent(terms); // Set isi terms sesuai pilihan
    setShowModal(true); // Tampilkan modal
  };

  const handleAccept = () => {
    if (termsAccepted) {
      setShowModal(false);
      setTermsAccepted(false); // Reset checkbox untuk penggunaan berikutnya
      window.location.href = redirectLink; // Redirect ke halaman
    } else {
      alert("Please agree to the Terms & Conditions to proceed.");
    }
  };

  return (
    <>
      <Head>
        <title>WSEEC REGISTRATION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="homeregist-section">
        <div className="wrapper">
          <div className="">
            <h2 className="">FORM REGISTRATION</h2>
            <h1 className="">Registration WSEEC</h1>
          </div>
        </div>
        <div className="wrapper">
          <div className="link-web mx-auto text-center">
            <Link href="/homeindo" legacyBehavior>
            <a className="btn btn-action text-center me-lg-5">
              Indonesia Participant{" "}
              <i className="fa-solid fa-earth-americas"></i>
            </a>
            </Link>
            <Link href="/homeinter" legacyBehavior>
            <a className="btn btn-action text-center me-lg-5">
              International Participant{" "}
              <i className="fa-solid fa-earth-americas"></i>
            </a>
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
